site_name: free-matrix-laws
site_url: https://slavakargin.github.io/free-matrix-laws/
repo_url: https://github.com/slavakargin/free-matrix-laws
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Notebooks:
    - Semicircle methods: notebooks/10_semicircle_methods.ipynb
  - API:
    - Transforms: api/transforms.md
    - Operator-valued maps: api/opvalued.md
    - Random Ensembles: api/ensembles.md
  - How-to: 
    - Overview: howto/index.md
    - Covariance map (Î·): howto/covariance_map.md
    - Semicircle Cauchy transform solver: howto/solve_cauchy_semicircle.md
    - Biased semicircle Cauch transform solver: howto/solve_cauchy_biased.md
    - Random Semicircle: howto/random_semicircle.md
markdown_extensions:
  - admonition
  - fenced_code             
  - pymdownx.superfences     
  - pymdownx.highlight      
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

